// Catalogo base de personajes femeninos - clasificacion general (sin contenido +18/hentai)
// Datos de edad/signo/fecha son aproximados segun informacion publica de cada franquicia;
// donde el canon no especifica el dato, se deja null o "Desconocida".
// La "popularidad" es un valor estimado (0-100) que puedes usar para calcular rarezas en tu gacha.

const characters = [
  // ---------------- ANIME ----------------
  {
    nombre: 'Sakura Haruno',
    edad: 17,
    signo: 'Aries',
    fechaNacimiento: '28-03',
    origen: 'Naruto',
    tipo: 'anime',
    sinopsis:
      'Kunoichi de la Hoja y aprendiz de la Quinta Hokage. Comienza como una ninja centrada en el estudio y evoluciona hasta convertirse en una de las mejores ninjas medicas, combinando fuerza sobrehumana con jutsus curativos.',
    popularidad: 78,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Hinata Hyuga',
    edad: 17,
    signo: 'Sagitario',
    fechaNacimiento: '27-12',
    origen: 'Naruto',
    tipo: 'anime',
    sinopsis:
      'Heredera del clan Hyuga, dueña del Byakugan. Timida en su juventud, crece hasta dominar el Junken y convertirse en un pilar emocional para su equipo, superando la presion de su clan.',
    popularidad: 74,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Tsunade',
    edad: 50,
    signo: 'Virgo',
    fechaNacimiento: '02-08',
    origen: 'Naruto',
    tipo: 'anime',
    sinopsis:
      'Quinta Hokage y una de los Sannin legendarios. Considerada la mejor ninja medica del mundo shinobi, oculta su edad real gracias a un jutsu, y carga con el peso de haber perdido a seres queridos en la guerra.',
    popularidad: 70,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Nami',
    edad: 20,
    signo: 'Cancer',
    fechaNacimiento: '03-07',
    origen: 'One Piece',
    tipo: 'anime',
    sinopsis:
      'Navegante de los Piratas de Sombrero de Paja. Su sueño es dibujar un mapa completo del mundo; de joven fue forzada a robar para los piratas de Arlong, lo que forjo su determinacion por la libertad.',
    popularidad: 85,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Nico Robin',
    edad: 30,
    signo: 'Piscis',
    fechaNacimiento: '06-02',
    origen: 'One Piece',
    tipo: 'anime',
    sinopsis:
      'Arqueologa y unica sobreviviente de la isla Ohara. Busca descifrar los Poneglyphs para revelar la verdadera historia del mundo, tras años siendo perseguida por el Gobierno Mundial.',
    popularidad: 82,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Boa Hancock',
    edad: 31,
    signo: 'Piscis',
    fechaNacimiento: '02-03',
    origen: 'One Piece',
    tipo: 'anime',
    sinopsis:
      'Emperatriz de Amazon Lily y una de los Shichibukai. Posee la fruta Mero Mero que petrifica a quien siente atraccion por ella; bajo su caracter orgulloso esconde el trauma de haber sido esclava.',
    popularidad: 80,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Bulma',
    edad: 16,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Dragon Ball',
    tipo: 'anime',
    sinopsis:
      'Genio cientifica e inventora de la Capsule Corp. Acompaña a Goku en la busqueda de las Esferas del Dragon, y con el tiempo se convierte en la mente detras de gran parte de la tecnologia del universo Dragon Ball.',
    popularidad: 75,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Android 18',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Dragon Ball Z',
    tipo: 'anime',
    sinopsis:
      'Androide creada por el Dr. Gero para destruir a Goku. Tras ser derrotada, se une a los Guerreros Z, se casa con Krilin y se convierte en madre, dejando atras su pasado como villana.',
    popularidad: 73,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Mikasa Ackerman',
    edad: 15,
    signo: 'Piscis',
    fechaNacimiento: '10-02',
    origen: 'Attack on Titan',
    tipo: 'anime',
    sinopsis:
      'Miembro del Cuerpo de Exploracion y una de las soldados mas fuertes de la humanidad. Su vida gira en torno a proteger a Eren Yeager, tras perder a su familia biologica en un ataque cuando era niña.',
    popularidad: 88,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Historia Reiss',
    edad: 15,
    signo: 'Enero',
    fechaNacimiento: 'Desconocida',
    origen: 'Attack on Titan',
    tipo: 'anime',
    sinopsis:
      'Heredera legitima de la familia real de las murallas. Pasa de ser una soldado insegura de si misma a asumir el trono, enfrentando el peso de la verdadera historia de su nacion.',
    popularidad: 65,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Ochaco Uraraka',
    edad: 16,
    signo: 'Capricornio',
    fechaNacimiento: '27-12',
    origen: 'My Hero Academia',
    tipo: 'anime',
    sinopsis:
      'Estudiante de la clase 1-A de U.A. con el Quirk "Ingravidez". Se esfuerza por convertirse en heroina profesional para dar una vida comoda a sus padres, mientras desarrolla sentimientos por Deku.',
    popularidad: 72,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Momo Yaoyorozu',
    edad: 16,
    signo: 'Virgo',
    fechaNacimiento: '01-09',
    origen: 'My Hero Academia',
    tipo: 'anime',
    sinopsis:
      'Vicepresidenta de la clase 1-A con el Quirk de creacion, capaz de generar objetos a partir de su propio cuerpo. Proviene de una familia adinerada y destaca por su inteligencia estrategica.',
    popularidad: 60,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Winry Rockbell',
    edad: 16,
    signo: 'Escorpio',
    fechaNacimiento: '11-11',
    origen: 'Fullmetal Alchemist',
    tipo: 'anime',
    sinopsis:
      'Ingeniera de automail y amiga de la infancia de los hermanos Elric. Perdio a sus padres en la guerra de Ishval y encontro su proposito reparando las protesis mecanicas de Edward.',
    popularidad: 68,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Riza Hawkeye',
    edad: 29,
    signo: 'Acuario',
    fechaNacimiento: '21-01',
    origen: 'Fullmetal Alchemist',
    tipo: 'anime',
    sinopsis:
      'Primer teniente del ejercito y francotiradora de elite, mano derecha del coronel Roy Mustang. Guarda un secreto sobre alquimia de fuego tatuado en su espalda por su propio padre.',
    popularidad: 71,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Misa Amane',
    edad: 19,
    signo: 'Escorpio',
    fechaNacimiento: '25-12',
    origen: 'Death Note',
    tipo: 'anime',
    sinopsis:
      'Idol y modelo japonesa que obtiene un Death Note y se convierte en la segunda Kira. Su devocion obsesiva por Light Yagami la lleva a cometer actos extremos en su nombre.',
    popularidad: 66,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Lucy Heartfilia',
    edad: 17,
    signo: 'Cancer',
    fechaNacimiento: '01-07',
    origen: 'Fairy Tail',
    tipo: 'anime',
    sinopsis:
      'Maga celestial miembro del gremio Fairy Tail, capaz de invocar espiritus estelares mediante llaves doradas. Escapo de una familia adinerada para vivir su propia aventura como maga.',
    popularidad: 74,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Erza Scarlet',
    edad: 19,
    signo: 'Escorpio',
    fechaNacimiento: '13-11',
    origen: 'Fairy Tail',
    tipo: 'anime',
    sinopsis:
      'Maga de re-equipamiento conocida como "Titania", una de las magas mas poderosas de Fairy Tail. Sobrevivio a la esclavitud en la Torre del Cielo, lo que forjo su caracter disciplinado y protector.',
    popularidad: 80,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Nezuko Kamado',
    edad: 14,
    signo: 'Aries',
    fechaNacimiento: '28-12',
    origen: 'Demon Slayer',
    tipo: 'anime',
    sinopsis:
      'Hermana menor de Tanjiro, convertida en demonio tras el ataque que aniquilo a su familia. A diferencia de otros demonios, logra resistir el impulso de atacar humanos y lucha junto a su hermano.',
    popularidad: 90,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Shinobu Kocho',
    edad: 18,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Demon Slayer',
    tipo: 'anime',
    sinopsis:
      'Pilar del Insecto en el Cuerpo de Cazadores de Demonios. Su espada esta impregnada de veneno de glicina, ya que carece de la fuerza para decapitar demonios; oculta un profundo dolor tras su sonrisa constante.',
    popularidad: 76,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Asuka Langley Soryu',
    edad: 14,
    signo: 'Cancer',
    fechaNacimiento: '04-12',
    origen: 'Neon Genesis Evangelion',
    tipo: 'anime',
    sinopsis:
      'Piloto del Eva-02 y prodigio de la NERV alemana. Su fachada de arrogancia y confianza esconde un profundo trauma infantil relacionado con la enfermedad y muerte de su madre.',
    popularidad: 77,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Rei Ayanami',
    edad: 14,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Neon Genesis Evangelion',
    tipo: 'anime',
    sinopsis:
      'Piloto del Eva-00, de personalidad callada y enigmatica. Su origen esta profundamente ligado a los secretos de NERV y a la propia historia de la humanidad en la serie.',
    popularidad: 79,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Misty',
    edad: 10,
    signo: 'Piscis',
    fechaNacimiento: '19-02',
    origen: 'Pokemon',
    tipo: 'anime',
    sinopsis:
      'Lider de gimnasio de Ciudad Celeste especializada en Pokemon de tipo agua. Acompaña a Ash en sus primeros viajes por Kanto, mostrando su caracter fuerte y su miedo particular a los bichos.',
    popularidad: 69,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'May',
    edad: 10,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Pokemon',
    tipo: 'anime',
    sinopsis:
      'Coordinadora Pokemon originaria de Hoenn. Comienza su viaje sin demasiado interes en los Pokemon, pero descubre su pasion por los Concursos Pokemon junto a Ash y Brock.',
    popularidad: 58,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Dawn',
    edad: 10,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Pokemon',
    tipo: 'anime',
    sinopsis:
      'Coordinadora Pokemon de Sinnoh que sigue los pasos de su madre, tambien una destacada coordinadora. Viaja junto a Ash y Brock combinando batallas con presentaciones de Concursos Pokemon.',
    popularidad: 55,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Usagi Tsukino',
    edad: 14,
    signo: 'Cancer',
    fechaNacimiento: '30-06',
    origen: 'Sailor Moon',
    tipo: 'anime',
    sinopsis:
      'Estudiante torpe y llorona que descubre ser la reencarnacion de la Princesa Serenity. Como Sailor Moon, lidera a las Sailor Scouts en la proteccion de la Tierra contra fuerzas oscuras.',
    popularidad: 81,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Rem',
    edad: 17,
    signo: 'Piscis',
    fechaNacimiento: '02-02',
    origen: 'Re:Zero',
    tipo: 'anime',
    sinopsis:
      'Demonio oni y sirvienta de la mansion Roswaal, junto a su hermana gemela Ram. Tras superar un profundo complejo de inferioridad respecto a su hermana, desarrolla una devocion absoluta por Subaru.',
    popularidad: 83,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Emilia',
    edad: 17,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Re:Zero',
    tipo: 'anime',
    sinopsis:
      'Media elfa candidata al trono real, acompañada por el espiritu Puck. Su parecido con la temida "Bruja de la Envidia" le trae discriminacion, pero lucha por demostrar su propio valor.',
    popularidad: 79,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Zero Two',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Darling in the Franxx',
    tipo: 'anime',
    sinopsis:
      'Piloto hibrida humano-Klaxosaur conocida como "la cazadora de mascotas" por sobrevivir a todos sus compañeros anteriores. Busca convertirse en completamente humana junto a Hiro.',
    popularidad: 84,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Videl',
    edad: 17,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Dragon Ball Z',
    tipo: 'anime',
    sinopsis:
      'Hija de Mr. Satan y compañera de Gohan. Aunque comienza sin poderes, entrena artes marciales y eventualmente aprende a volar usando ki, convirtiendose en una luchadora competente.',
    popularidad: 62,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Chi-Chi',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Dragon Ball',
    tipo: 'anime',
    sinopsis:
      'Hija del Rey Ox y esposa de Goku. Entrenada en artes marciales desde niña, con el tiempo se enfoca en la crianza y educacion de sus hijos Gohan y Goten, priorizando sus estudios sobre la pelea.',
    popularidad: 57,
    imagenUrl: '',
    rarity: 'SR',
  },

  // ---------------- VIDEOJUEGOS ----------------
  {
    nombre: 'Princess Zelda',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'The Legend of Zelda',
    tipo: 'videojuego',
    sinopsis:
      'Princesa de Hyrule y portadora del Trifuerza de la Sabiduria. A lo largo de distintas encarnaciones, combate junto a Link contra Ganon para proteger su reino, adoptando en ocasiones identidades secretas como Sheik.',
    popularidad: 86,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Samus Aran',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Metroid',
    tipo: 'videojuego',
    sinopsis:
      'Cazarrecompensas galactica criada por los Chozo tras la destruccion de su colonia natal. Enfrenta a los Piratas Espaciales y a los Metroid enfundada en su icónica armadura de poder.',
    popularidad: 82,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Lara Croft',
    edad: 21,
    signo: 'Acuario',
    fechaNacimiento: '14-02',
    origen: 'Tomb Raider',
    tipo: 'videojuego',
    sinopsis:
      'Arqueologa y aventurera britanica que explora tumbas y ruinas antiguas en busca de reliquias perdidas. Su primera gran expedicion en Yamatai la transforma de academica en superviviente curtida.',
    popularidad: 85,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Chun-Li',
    edad: 22,
    signo: null,
    fechaNacimiento: '01-03',
    origen: 'Street Fighter',
    tipo: 'videojuego',
    sinopsis:
      'Agente de la Interpol y experta en artes marciales conocida como "la mujer mas fuerte del mundo". Busca vengar la muerte de su padre a manos de la organizacion criminal Shadaloo.',
    popularidad: 80,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Cammy White',
    edad: 21,
    signo: null,
    fechaNacimiento: '06-12',
    origen: 'Street Fighter',
    tipo: 'videojuego',
    sinopsis:
      'Ex-agente de Shadaloo creada como clon de combate, hoy miembro de una unidad especial britanica. Lucha por descubrir su pasado y liberar a otras clones creadas por la misma organizacion.',
    popularidad: 74,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Bayonetta',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Bayonetta',
    tipo: 'videojuego',
    sinopsis:
      'Bruja Umbra con siglos de vida, especializada en combate contra angeles usando armas de fuego y magia de cabello. Investiga su pasado perdido mientras se enfrenta a las fuerzas del paraiso.',
    popularidad: 75,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Aloy',
    edad: 19,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Horizon Zero Dawn',
    tipo: 'videojuego',
    sinopsis:
      'Cazadora criada al margen de su tribu Nora, experta en enfrentar maquinas robóticas con arco y trampas. Investiga el misterio de su nacimiento y el colapso de una civilizacion tecnologica antigua.',
    popularidad: 78,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Jill Valentine',
    edad: 23,
    signo: null,
    fechaNacimiento: '14-02',
    origen: 'Resident Evil',
    tipo: 'videojuego',
    sinopsis:
      'Ex miembro del equipo S.T.A.R.S. de la policia de Raccoon City. Sobrevive a la mansion Spencer y años despues a la persecucion de Nemesis, convirtiendose en un icono del genero de terror.',
    popularidad: 79,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Ada Wong',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Resident Evil',
    tipo: 'videojuego',
    sinopsis:
      'Espia independiente de motivaciones ambiguas, vinculada sentimentalmente a Leon Kennedy. Trabaja para distintas organizaciones interesadas en el virus, siempre unos pasos adelante de todos.',
    popularidad: 76,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Tifa Lockhart',
    edad: 20,
    signo: 'Cancer',
    fechaNacimiento: '03-05',
    origen: 'Final Fantasy VII',
    tipo: 'videojuego',
    sinopsis:
      'Amiga de la infancia de Cloud y luchadora cuerpo a cuerpo, dueña del bar Seventh Heaven. Miembro fundamental de Avalanche, el grupo eco-terrorista que se enfrenta a la corporacion Shinra.',
    popularidad: 83,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Aerith Gainsborough',
    edad: 22,
    signo: 'Piscis',
    fechaNacimiento: '07-02',
    origen: 'Final Fantasy VII',
    tipo: 'videojuego',
    sinopsis:
      'Ultima Cetra, un pueblo antiguo con un vinculo especial con el Planeta. Vendedora de flores en los suburbios de Midgar, su destino queda entrelazado con la amenaza de Sefirot sobre el mundo.',
    popularidad: 81,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: '2B (YoRHa No.2 Type B)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'NieR: Automata',
    tipo: 'videojuego',
    sinopsis:
      'Androide de combate de la unidad YoRHa, enviada a la Tierra para combatir maquinas junto a 9S. Su mision oculta como "ejecutora" pesa sobre la relacion que desarrolla con su compañero.',
    popularidad: 77,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Princess Peach',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Super Mario',
    tipo: 'videojuego',
    sinopsis:
      'Gobernante del Reino Champiñon, frecuentemente secuestrada por Bowser. Lejos de ser solo una damisela, ha demostrado ser una luchadora capaz en varios spin-offs y titulos deportivos.',
    popularidad: 80,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Rosalina',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Super Mario Galaxy',
    tipo: 'videojuego',
    sinopsis:
      'Guardiana cosmica que viaja por el universo junto a los Lumas en su Observatorio. Adopto a estas criaturas estelares tras la muerte de su madre, cuidandolas como su propia familia.',
    popularidad: 63,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Widowmaker',
    edad: 34,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Overwatch',
    tipo: 'videojuego',
    sinopsis:
      'Francotiradora de Talon, antigua agente de Overwatch condicionada mediante lavado de cerebro para asesinar a su propio esposo. Sus emociones fueron suprimidas quimicamente para convertirla en un arma perfecta.',
    popularidad: 75,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Tracer (Lena Oxton)',
    edad: 26,
    signo: null,
    fechaNacimiento: '24-05',
    origen: 'Overwatch',
    tipo: 'videojuego',
    sinopsis:
      'Piloto britanica que tras un accidente con el Slipstream queda desincronizada del tiempo. Un dispositivo cronal le permite acelerar, retroceder y parpadear en el tiempo, convirtiendola en heroina veloz de Overwatch.',
    popularidad: 84,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Mercy (Angela Ziegler)',
    edad: 37,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Overwatch',
    tipo: 'videojuego',
    sinopsis:
      'Medica y cientifica suiza pionera en tecnologia de nano-biotica. Como miembro fundador de Overwatch, se dedica a sanar a sus compañeros en batalla mientras lidia con el dilema etico de su propia tecnologia.',
    popularidad: 78,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'D.Va (Hana Song)',
    edad: 19,
    signo: null,
    fechaNacimiento: '06-12',
    origen: 'Overwatch',
    tipo: 'videojuego',
    sinopsis:
      'Ex jugadora profesional de esports surcoreana reclutada para pilotar un mecha de combate MEKA. Defiende Busan de invasiones Omnic combinando su fama de streamer con habilidades militares.',
    popularidad: 82,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Jinx',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'League of Legends / Arcane',
    tipo: 'videojuego',
    sinopsis:
      'Criminal caotica de los bajos fondos de Zaun, experta en armamento improvisado. Su historia esta marcada por la fractura de su relacion con su hermana Vi tras una serie de tragedias en su infancia.',
    popularidad: 83,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Vi',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'League of Legends / Arcane',
    tipo: 'videojuego',
    sinopsis:
      'Ejecutora de la policia de Piltover con guanteletes de combate propios. Tras años en prision, retoma la busqueda de su hermana perdida, Powder, sin saber que se ha convertido en Jinx.',
    popularidad: 81,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Nakoruru',
    edad: 16,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Samurai Shodown',
    tipo: 'videojuego',
    sinopsis:
      'Joven guerrera Ainu que protege la naturaleza junto a su halcon Mamahaha. Lucha en el torneo para restaurar el equilibrio espiritual entre los humanos y la naturaleza de su tierra natal.',
    popularidad: 58,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Morrigan Aensland',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Darkstalkers',
    tipo: 'videojuego',
    sinopsis:
      'Sucubo heredera del trono del Reino Makai. Abandona su castillo para explorar el mundo humano y descubrir su propia identidad, lejos de las obligaciones de la nobleza demoniaca.',
    popularidad: 62,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Elizabeth Comstock',
    edad: 19,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'BioShock Infinite',
    tipo: 'videojuego',
    sinopsis:
      'Joven encerrada toda su vida en la ciudad flotante de Columbia, dotada de la habilidad de abrir "rasgones" entre realidades alternativas. Su rescate desencadena una historia sobre destino, culpa y multiples universos.',
    popularidad: 70,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Ellie Williams',
    edad: 14,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'The Last of Us',
    tipo: 'videojuego',
    sinopsis:
      'Adolescente inmune a la infeccion de cordyceps que asola a la humanidad. Su viaje junto a Joel a traves de un Estados Unidos post-apocaliptico explora temas de perdida, supervivencia y esperanza.',
    popularidad: 87,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },

  // ---------------- COMICS ----------------
  {
    nombre: 'Wonder Woman (Diana Prince)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Princesa amazona de Themyscira, moldeada en arcilla y dotada de vida por los dioses griegos. Embajadora de paz entre el mundo de las Amazonas y el de los humanos, y una de las heroinas fundadoras de la Liga de la Justicia.',
    popularidad: 88,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Supergirl (Kara Zor-El)',
    edad: 21,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Prima de Superman, enviada desde Krypton para proteger a su primo pequeño pero que llega a la Tierra ya adulta debido a un retraso en su viaje. Lucha por encontrar su lugar entre dos mundos.',
    popularidad: 76,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Batgirl (Barbara Gordon)',
    edad: 21,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Hija del comisionado Gordon, bibliotecaria de dia y vigilante de Gotham de noche. Tras un ataque del Joker que la deja parapléjica, se reinventa como la hacker Oracle antes de recuperar su rol como Batgirl.',
    popularidad: 74,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Black Widow (Natasha Romanoff)',
    edad: null,
    signo: null,
    fechaNacimiento: '22-11',
    origen: 'Marvel Comics',
    tipo: 'comic',
    sinopsis:
      'Ex espia sovietica entrenada desde la infancia en el Cuarto Rojo. Tras desertar hacia Occidente, se convierte en miembro clave de los Vengadores, buscando redimir su pasado de agente encubierta.',
    popularidad: 85,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Captain Marvel (Carol Danvers)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics',
    tipo: 'comic',
    sinopsis:
      'Ex piloto de la fuerza aerea que obtiene poderes cosmicos tras un accidente con tecnologia Kree. Se convierte en una de las heroinas mas poderosas de la Tierra, capaz de vuelo, fuerza sobrehumana y disparo de energia.',
    popularidad: 80,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Storm (Ororo Munroe)',
    edad: null,
    signo: null,
    fechaNacimiento: '10-05',
    origen: 'Marvel Comics (X-Men)',
    tipo: 'comic',
    sinopsis:
      'Mutante capaz de controlar el clima, venerada como diosa en su juventud en Africa. Lider de los X-Men en multiples etapas, equilibra su poder casi divino con un profundo sentido de responsabilidad hacia los demas.',
    popularidad: 79,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Harley Quinn (Harleen Quinzel)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Ex psiquiatra de Arkham Asylum que se enamoro obsesivamente de uno de sus pacientes, el Joker, convirtiendose en su complice. Con el tiempo se libera de esa relacion toxica y forja su propio camino como antiheroina.',
    popularidad: 89,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Catwoman (Selina Kyle)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Ladrona experta de Gotham City con un codigo moral propio. Mantiene una compleja relacion de rivalidad y romance con Batman, moviendose constantemente entre el crimen y la redencion.',
    popularidad: 83,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Jean Grey',
    edad: null,
    signo: null,
    fechaNacimiento: '03-11',
    origen: 'Marvel Comics (X-Men)',
    tipo: 'comic',
    sinopsis:
      'Mutante telepata y telequinetica, una de las miembros originales de los X-Men. Su vinculo con la entidad cosmica Fenix la convierte en una de las mutantes mas poderosas y trágicas del universo Marvel.',
    popularidad: 78,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'She-Hulk (Jennifer Walters)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics',
    tipo: 'comic',
    sinopsis:
      'Abogada prima de Bruce Banner que recibe una transfusion de sangre gamma para salvar su vida. A diferencia de su primo, conserva su personalidad e inteligencia al transformarse, usando sus poderes tanto en la corte como en el combate.',
    popularidad: 72,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Rogue (Anna Marie)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics (X-Men)',
    tipo: 'comic',
    sinopsis:
      'Mutante capaz de absorber memorias, poderes y energia vital con el contacto de su piel, lo que la condena a una vida de aislamiento fisico. Miembro de los X-Men, busca controlar su don para poder acercarse a los demas.',
    popularidad: 75,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Scarlet Witch (Wanda Maximoff)',
    edad: null,
    signo: null,
    fechaNacimiento: '10-02',
    origen: 'Marvel Comics',
    tipo: 'comic',
    sinopsis:
      'Mutante con capacidad de alterar la realidad mediante magia del caos. Su historia esta marcada por perdidas devastadoras que la llevan a convertirse tanto en heroina como, en ciertas etapas, en amenaza para toda la realidad.',
    popularidad: 84,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Poison Ivy (Pamela Isley)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Ex botanica transformada por experimentos que le otorgan control sobre plantas y toxinas. Ecoterrorista convencida de la superioridad de la vida vegetal sobre la humanidad, es una de las villanas recurrentes de Gotham.',
    popularidad: 73,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Zatanna Zatara',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Hechicera e ilusionista que lanza sus conjuros pronunciando las palabras al reves. Hija de un mago legendario, es miembro frecuente de la Liga de la Justicia y experta en la magia mas alla de la ciencia.',
    popularidad: 65,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Raven',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics (Teen Titans)',
    tipo: 'comic',
    sinopsis:
      'Hija de un demonio interdimensional y una sacerdotisa humana, debe mantener sus emociones bajo control para evitar liberar sus poderes destructivos. Miembro fundamental de los Jovenes Titanes.',
    popularidad: 77,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Starfire (Koriand\'r)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics (Teen Titans)',
    tipo: 'comic',
    sinopsis:
      'Princesa alienigena del planeta Tamaran que escapa de la esclavitud para unirse a los Jovenes Titanes en la Tierra. Su alegria y optimismo contrastan con el oscuro pasado de guerra de su planeta natal.',
    popularidad: 74,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Spider-Gwen (Gwen Stacy)',
    edad: 17,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics',
    tipo: 'comic',
    sinopsis:
      'En un universo alternativo, Gwen Stacy es quien recibe la picadura de la araña radiactiva en lugar de Peter Parker. Se convierte en Spider-Woman mientras lidia con la culpa de tragedias que ocurren de forma diferente a la linea principal.',
    popularidad: 82,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Mary Jane Watson',
    edad: null,
    signo: null,
    fechaNacimiento: '20-04',
    origen: 'Marvel Comics',
    tipo: 'comic',
    sinopsis:
      'Actriz y modelo, interes amoroso historico de Peter Parker. A pesar de no tener poderes, es una constante fuente de apoyo emocional y ha sido retratada en distintas epocas como pieza clave en la vida de Spider-Man.',
    popularidad: 70,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Emma Frost',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics (X-Men)',
    tipo: 'comic',
    sinopsis:
      'Mutante telepata que puede transformar su piel en un diamante organico invulnerable. Ex villana conocida como la "Reina Blanca", se redime con el tiempo hasta convertirse en profesora y lider de los X-Men.',
    popularidad: 76,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Psylocke (Betsy Braddock)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics (X-Men)',
    tipo: 'comic',
    sinopsis:
      'Mutante telepata britanica cuya mente termino alojada en un cuerpo ninja tras un complejo intercambio corporal. Combina poderes psiquicos con un dominio letal de las artes marciales y la espada psionica.',
    popularidad: 71,
    imagenUrl: '',
    rarity: 'CR',
  },

  // ---------------- AMPLIACION DEL CATALOGO ----------------
  {
    nombre: 'Makima',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Chainsaw Man',
    tipo: 'anime',
    sinopsis:
      'Jefa de la division de Seguridad Publica que recluta a Denji tras la muerte de su antiguo compañero canino. Detras de su calma perpetua esconde una naturaleza mucho mas antigua y peligrosa de lo que aparenta.',
    popularidad: 91,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Power',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Chainsaw Man',
    tipo: 'anime',
    sinopsis:
      'Fiend con forma de sangre, compañera de piso de Denji tan caotica como egoista. Bajo su fachada arrogante y su gato Meowy esconde un lazo genuino de lealtad hacia los pocos que considera suyos.',
    popularidad: 79,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Yor Forger',
    edad: 27,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Spy x Family',
    tipo: 'anime',
    sinopsis:
      'Asesina de elite conocida como "la Princesa Espina", que acepta un matrimonio de conveniencia sin saber que su esposo es un espia. Equilibra su vida diaria de oficinista con misiones letales secretas.',
    popularidad: 86,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Anya Forger',
    edad: 6,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Spy x Family',
    tipo: 'anime',
    sinopsis:
      'Niña telepata adoptada por una familia formada por un espia y una asesina, sin que ninguno sepa la verdad del otro. Su capacidad de leer mentes la mantiene constantemente al tanto de los secretos familiares.',
    popularidad: 84,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Marin Kitagawa',
    edad: 16,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'My Dress-Up Darling',
    tipo: 'anime',
    sinopsis:
      'Estudiante popular y fanatica declarada del cosplay que descubre las habilidades de costura de un compañero introvertido. Su entusiasmo genuino por su hobby rompe barreras sociales entre ambos.',
    popularidad: 72,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Kaguya Shinomiya',
    edad: 18,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Kaguya-sama: Love is War',
    tipo: 'anime',
    sinopsis:
      'Vicepresidenta del consejo estudiantil, heredera de una poderosa familia, atrapada en una guerra psicologica de orgullo contra el presidente del consejo para ver quien confiesa primero sus sentimientos.',
    popularidad: 77,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Chika Fujiwara',
    edad: 17,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Kaguya-sama: Love is War',
    tipo: 'anime',
    sinopsis:
      'Secretaria del consejo estudiantil, tan brillante como excentrica. Su energia impredecible suele desestabilizar los planes cuidadosamente calculados de sus compañeros de consejo.',
    popularidad: 59,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Violet Evergarden',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Violet Evergarden',
    tipo: 'anime',
    sinopsis:
      'Ex soldado convertida en "escritora de cartas automatica" tras la guerra, que viaja transcribiendo los sentimientos de otros mientras intenta comprender el significado de unas palabras que escucho una vez.',
    popularidad: 75,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Yuki Nagato',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'The Melancholy of Haruhi Suzumiya',
    tipo: 'anime',
    sinopsis:
      'Interfaz humanoide creada por una entidad de datos interestelar para observar a Haruhi Suzumiya. De expresion casi inalterable, posee capacidades practicamente ilimitadas que rara vez muestra.',
    popularidad: 48,
    imagenUrl: '',
    rarity: 'R',
  },
  {
    nombre: 'Mio Akiyama',
    edad: 17,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'K-On!',
    tipo: 'anime',
    sinopsis:
      'Bajista y letrista del club de musica ligera, tan talentosa como timida en el escenario. Su caracter reservado contrasta con la energia despreocupada del resto de sus compañeras de banda.',
    popularidad: 44,
    imagenUrl: '',
    rarity: 'R',
  },
  {
    nombre: 'Chiyo Sakura',
    edad: 16,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Monthly Girls\' Nozaki-kun',
    tipo: 'anime',
    sinopsis:
      'Estudiante que confiesa sus sentimientos a un compañero sin saber que es un mangaka de shojo en secreto, y termina reclutada como su asistente de dibujo en vez de recibir la respuesta que esperaba.',
    popularidad: 38,
    imagenUrl: '',
    rarity: 'R',
  },
  {
    nombre: 'Kim Possible',
    edad: 16,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Kim Possible',
    tipo: 'anime',
    sinopsis:
      'Estudiante de secundaria que en su tiempo libre desbarata planes de villanos alrededor del mundo. Combina tareas escolares con misiones de espionaje gracias a su lema: "puedo hacer cualquier cosa".',
    popularidad: 41,
    imagenUrl: '',
    rarity: 'R',
  },
  {
    nombre: 'Ciri (Cirilla Fiona Elen Riannon)',
    edad: 18,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'The Witcher',
    tipo: 'videojuego',
    sinopsis:
      'Princesa de Cintra entrenada como bruja por Geralt de Rivia, portadora de una sangre antigua con capacidad de viajar entre mundos. Su destino esta ligado a fuerzas que exceden a reinos y brujos por igual.',
    popularidad: 89,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Triss Merigold',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'The Witcher',
    tipo: 'videojuego',
    sinopsis:
      'Hechicera del continente, amiga cercana y a veces amante de Geralt, sobreviviente del pogromo de magos en Novigrado. Su lealtad a Ciri y a la Hermandad de Brujas la coloca en el centro de multiples conflictos politicos.',
    popularidad: 78,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Yennefer de Vengerberg',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'The Witcher',
    tipo: 'videojuego',
    sinopsis:
      'Poderosa hechicera de origen humilde, transformada radicalmente por la magia que la formo. Su relacion tormentosa con Geralt y su busqueda de fertilidad perdida marcan gran parte de su historia personal.',
    popularidad: 81,
    imagenUrl: '',
    rarity: 'SSR',
  },
  {
    nombre: 'Kassandra',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: "Assassin's Creed Odyssey",
    tipo: 'videojuego',
    sinopsis:
      'Mercenaria espartana descendiente de una estirpe ligada a un antiguo culto precursor. Recorre la Grecia clasica en busca de su familia fragmentada mientras se ve envuelta en la Guerra del Peloponeso.',
    popularidad: 73,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Chell',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Portal',
    tipo: 'videojuego',
    sinopsis:
      'Sujeto de pruebas silenciosa de los laboratorios Aperture Science, sometida a una serie de pruebas con el Dispositivo de Manipulacion de Portales bajo la supervision de una inteligencia artificial hostil.',
    popularidad: 52,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Alyx Vance',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Half-Life',
    tipo: 'videojuego',
    sinopsis:
      'Hija de un cientifico clave de la resistencia contra la ocupacion Combine, y aliada inseparable de Gordon Freeman. Combina ingenio tecnico con habilidades de combate en la lucha por liberar a la humanidad.',
    popularidad: 47,
    imagenUrl: '',
    rarity: 'R',
  },
  {
    nombre: 'Venti',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Genshin Impact',
    tipo: 'videojuego',
    sinopsis:
      'Bardo itinerante en Mondstadt, en realidad el Arconte Anemo que vela en secreto por la libertad de la ciudad. Equilibra su identidad divina milenaria con una vida despreocupada dedicada al vino y la musica.',
    popularidad: 90,
    imagenUrl: '',
    rarity: 'SSR_SECRET',
  },
  {
    nombre: 'Raiden Shogun',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Genshin Impact',
    tipo: 'videojuego',
    sinopsis:
      'Arconte Electro de Inazuma, que busca la eternidad encerrando a su nacion en un plano ilusorio inmutable. Su busqueda de un ideal absoluto la enfrenta directamente con el Viajero.',
    popularidad: 94,
    imagenUrl: '',
    rarity: 'UR',
  },
  {
    nombre: 'Jett',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Valorant',
    tipo: 'videojuego',
    sinopsis:
      'Agente coreana especializada en movilidad extrema gracias al control del viento, que se une al equipo de agentes tras la aparicion de una amenaza global conocida como el Vientre.',
    popularidad: 68,
    imagenUrl: '',
    rarity: 'CR',
  },

  {
    nombre: 'Ms. Marvel (Kamala Khan)',
    edad: 16,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics',
    tipo: 'comic',
    sinopsis:
      'Adolescente de Jersey City y fanatica de los superheroes que obtiene poderes de elongacion y cambio de forma. Su entusiasmo genuino por ser heroina contrasta con el peso de proteger a su propia comunidad.',
    popularidad: 74,
    imagenUrl: '',
    rarity: 'CR',
  },
  {
    nombre: 'Squirrel Girl (Doreen Green)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics',
    tipo: 'comic',
    sinopsis:
      'Heroina con poderes hibridos de ardilla, conocida en el universo Marvel por derrotar a villanos que otros consideran invencibles gracias a su ingenio y su ejercito de ardillas aliadas.',
    popularidad: 42,
    imagenUrl: '',
    rarity: 'R',
  },
  {
    nombre: 'Domino (Neena Thurman)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'Marvel Comics (X-Force)',
    tipo: 'comic',
    sinopsis:
      'Mutante mercenaria cuya habilidad manipula la probabilidad a su favor, haciendola parecer extraordinariamente afortunada en combate. Miembro recurrente de equipos paramilitares mutantes como X-Force.',
    popularidad: 63,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Vixen (Mari McCabe)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Heroina que canaliza un amuleto ancestral africano para replicar las habilidades de cualquier animal del reino salvaje. Modelo internacional que combina su carrera publica con misiones junto a la Liga de la Justicia.',
    popularidad: 39,
    imagenUrl: '',
    rarity: 'R',
  },
  {
    nombre: 'Huntress (Helena Bertinelli)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Unica sobreviviente de una familia asesinada por la mafia, se entrena en artes marciales y ballesta para impartir su propia version brutal de justicia en Gotham, chocando frecuentemente con los metodos de Batman.',
    popularidad: 61,
    imagenUrl: '',
    rarity: 'SR',
  },
  {
    nombre: 'Power Girl (Kara Zor-L)',
    edad: null,
    signo: null,
    fechaNacimiento: 'Desconocida',
    origen: 'DC Comics',
    tipo: 'comic',
    sinopsis:
      'Kryptoniana de un universo paralelo, prima alternativa de Superman que termina varada en la Tierra principal tras el colapso de su realidad de origen. Dirige su propia empresa tecnologica cuando no combate el crimen.',
    popularidad: 55,
    imagenUrl: '',
    rarity: 'SR',
  },
];

module.exports = characters;
